'use strict';

const cron = require('node-cron');
const { getDb } = require('../config/firebase');
const logger = require('../utils/logger');
const PDFDocument = require('pdfkit');

async function generateReport(customer, period, startDate, endDate, stats) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      let pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });

    const brandColor = '#ea580c'; // Orange brand color
    const darkGray = '#1e293b';
    const lightGray = '#64748b';
    const bgGray = '#f8fafc';

    // Header Graphic
    doc.rect(0, 0, doc.page.width, 10).fill(brandColor);

    // Title Section
    doc.fontSize(28).fillColor(darkGray).font('Helvetica-Bold').text('OneRepute', 50, 50);
    doc.fontSize(10).fillColor(brandColor).font('Helvetica-Bold').text('ANALYTICS REPORT', 50, 85, { letterSpacing: 2 });

    // Customer & Period Info
    doc.fontSize(16).fillColor(darkGray).font('Helvetica-Bold').text(customer.name || 'Customer', doc.page.width - 250, 50, { align: 'right' });
    doc.fontSize(10).fillColor(lightGray).font('Helvetica').text(`${period.toUpperCase()} PERFORMANCE`, doc.page.width - 250, 70, { align: 'right' });
    doc.fontSize(10).fillColor(lightGray).text(`${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`, doc.page.width - 250, 85, { align: 'right' });

    doc.moveTo(50, 110).lineTo(doc.page.width - 50, 110).lineWidth(1).strokeColor('#e2e8f0').stroke();

    // Summary Section
    doc.fontSize(14).fillColor(darkGray).font('Helvetica-Bold').text('Executive Summary', 50, 130);

    // Draw Metric Boxes
    const drawMetric = (x, y, label, value, subtext) => {
      doc.roundedRect(x, y, 150, 80, 8).fill(bgGray);
      doc.fillColor(lightGray).font('Helvetica').fontSize(10).text(label, x + 15, y + 15);
      doc.fillColor(darkGray).font('Helvetica-Bold').fontSize(24).text(value, x + 15, y + 35);
      if (subtext) {
        doc.fillColor(brandColor).font('Helvetica-Bold').fontSize(9).text(subtext, x + 15, y + 60);
      }
    };

    drawMetric(50, 160, 'Total Reviews', stats.totalReviews.toString(), 'Collected this period');
    drawMetric(215, 160, 'Average Rating', stats.avgRating.toFixed(1) + ' ★', 'Across all outlets');
    drawMetric(380, 160, 'AI Handled', stats.aiHandled + '%', 'Automated responses');

    // Outlet Breakdown Section
    doc.fontSize(14).fillColor(darkGray).font('Helvetica-Bold').text('Outlet Breakdown', 50, 270);
    
    // Table Header
    const tableY = 300;
    doc.roundedRect(50, tableY, doc.page.width - 100, 30, 4).fill(brandColor);
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(10);
    doc.text('OUTLET NAME', 65, tableY + 10);
    doc.text('REVIEWS', 250, tableY + 10);
    doc.text('RATING', 350, tableY + 10);
    doc.text('AI MANAGED', 450, tableY + 10);

    let currentY = tableY + 40;
    
    if (stats.outlets.length === 0) {
      doc.fillColor(lightGray).font('Helvetica').fontSize(10).text('No outlet data available for this period.', 65, currentY);
    }

    stats.outlets.forEach((outlet, i) => {
      if (currentY > doc.page.height - 100) {
        doc.addPage();
        currentY = 50;
      }
      
      if (i % 2 === 0) {
        doc.rect(50, currentY - 10, doc.page.width - 100, 30).fill(bgGray);
      }
      
      doc.fillColor(darkGray).font('Helvetica-Bold').fontSize(10);
      doc.text(outlet.name, 65, currentY, { width: 170, truncate: true });
      doc.fillColor(lightGray).font('Helvetica');
      doc.text(outlet.reviews.toString(), 250, currentY);
      doc.text(outlet.avgRating.toFixed(1) + ' ★', 350, currentY);
      doc.text(outlet.aiHandled + '%', 450, currentY);
      
      currentY += 30;
    });

    // Footer
    doc.fontSize(8).fillColor(lightGray).font('Helvetica').text(
      `Generated by OneRepute AI on ${new Date().toLocaleString()}`,
      50,
      doc.page.height - 50,
      { align: 'center' }
    );

    doc.end();
  });
}

async function triggerReportGeneration(period) {
  const db = getDb();
  logger.info(`[ReportCron] Starting ${period} report generation...`);
  try {
    const customersSnap = await db.collection('customers').get();
    let count = 0;
    for (const doc of customersSnap.docs) {
      const customer = doc.data();
      const startDate = new Date();
      startDate.setDate(startDate.getDate() - (period === 'weekly' ? 7 : 30));
      const endDate = new Date();
      
      // Gather real stats from Firestore for this customer
      const outletsSnap = await db.collection('outlets').where('customerId', '==', doc.id).get();
      let totalReviews = 0;
      let totalRatingSum = 0;
      let aiResponses = 0;
      
      const outletStats = [];

      for (const outletDoc of outletsSnap.docs) {
        const outlet = outletDoc.data();
        
        // Fetch reviews for this outlet within the period
        const reviewsSnap = await db.collection('reviews')
          .where('outletId', '==', outletDoc.id)
          .where('createdAt', '>=', startDate)
          .where('createdAt', '<=', endDate)
          .get();
          
        let oReviews = 0;
        let oRatingSum = 0;
        let oAiResponses = 0;

        reviewsSnap.forEach(rDoc => {
          const r = rDoc.data();
          oReviews++;
          oRatingSum += Number(r.rating || 0);
          if (r.aiResponse || ['responded', 'suggested'].includes(r.status)) {
            oAiResponses++;
          }
        });

        totalReviews += oReviews;
        totalRatingSum += oRatingSum;
        aiResponses += oAiResponses;

        outletStats.push({
          name: outlet.name || 'Unknown',
          reviews: oReviews,
          avgRating: oReviews > 0 ? oRatingSum / oReviews : 0,
          aiHandled: oReviews > 0 ? Math.round((oAiResponses / oReviews) * 100) : 0
        });
      }

      const stats = {
        totalReviews,
        avgRating: totalReviews > 0 ? totalRatingSum / totalReviews : 0,
        aiHandled: totalReviews > 0 ? Math.round((aiResponses / totalReviews) * 100) : 0,
        outlets: outletStats
      };

      const pdfBuffer = await generateReport(customer, period, startDate, endDate, stats);
      
      // In a real scenario, upload pdfBuffer to cloud storage and save URL.
      // Here we just save metadata
      await db.collection('reports').add({
        customerId: doc.id,
        customerName: customer.name,
        period,
        startDate,
        endDate,
        createdAt: new Date(),
        status: 'Generated',
        url: 'https://example.com/mock-report.pdf' // Mock URL
      });
      count++;
    }
    logger.info(`[ReportCron] Finished generating ${count} ${period} reports.`);
  } catch (err) {
    logger.error('[ReportCron] Error generating reports', { error: err.message });
  }
}

function initReportJobs() {
  // Weekly on Sunday at midnight
  cron.schedule('0 0 * * 0', () => {
    triggerReportGeneration('weekly');
  });

  // Monthly on the 1st at midnight
  cron.schedule('0 0 1 * *', () => {
    triggerReportGeneration('monthly');
  });
  
  logger.info('[ReportCron] Initialized weekly and monthly report cron jobs.');
}

module.exports = {
  initReportJobs,
  triggerReportGeneration
};
